
package GUI;

import Fecha.FuncionFecha;
import ModeloTablaPuesto.CeldasRenderTablePuesto;
import ModeloTablaCliente.CeldasRenderTableCliente;
import Filtrado.Filtrado;
import ModeloTablaPuesto.ModelTablePuesto;
import ModeloTablaCliente.ModelTableCliente;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.TableRowSorter;
import mercadoabasto.mercado.Mercado;
import mercadoabasto.clientes.*;
import mercadoabasto.exepciones.*;
import mercadoabasto.mercado.ResponsableAlquiler;
import mercadoabasto.mercado.*;


/**
 *
 * @author Daniel Juarez
 */
public class AgregarContrato extends javax.swing.JInternalFrame {

    private Mercado mercado;
    private FuncionFecha funcionFecha;
    private ModelTablePuesto modeloTablaPuesto;
    private ModelTableCliente modeloTablaClientes;
    private TableRowSorter trsFiltro;
    private TableRowSorter trsFiltroClientes;
    private String elementoSeleccionado;
    private LocalDate fechaInicioContrato;
    private LocalDate fechaFinContrato;
   
    public AgregarContrato(Mercado mercado) {
        initComponents();
        setResizable(false);
        this.mercado = mercado; 
           
        
        cargarDatosDelResponsable();
        cargarNumeroDeContrato();
        funcionFecha = new FuncionFecha();
        
        //TABLA
            modeloTablaPuesto = new ModelTablePuesto();
            tablaPuesto.setModel(modeloTablaPuesto);
            tablaPuesto.setDefaultRenderer(Object.class,new CeldasRenderTablePuesto(this.mercado,this.comboSector));
            trsFiltro = new TableRowSorter(tablaPuesto.getModel());
            tablaPuesto.setRowSorter(trsFiltro);
            
            modeloTablaClientes = new ModelTableCliente();
            tablaClientes.setModel(modeloTablaClientes);
            trsFiltroClientes = new TableRowSorter(tablaClientes.getModel());
            tablaClientes.setRowSorter(trsFiltroClientes);
            tablaClientes.setDefaultRenderer(Object.class , new CeldasRenderTableCliente());
       
        //COMBO 
            comboSector.setModel(MenuPrincipal.modeloCombo);
   
    
       //Eventos de Teclado   
            txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
    
            Filtrado.filtrarPorNumeroPuesto(txtBusqueda, trsFiltro);
            }
            });
            
            txtBusquedaClientes.addKeyListener(new KeyAdapter(){
                @Override
                public void keyReleased(final KeyEvent e){
                    Filtrado.filtrarClientesPorCuilCuit(txtBusquedaClientes, trsFiltroClientes);
                }
            });
            
            modeloTablaClientes.cargarDatosDeClientes(this.mercado.getClientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPuesto = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroContrato = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        comboSector = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        btnCerrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnNuevoCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBusquedaClientes = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 255));
        setTitle("AGREGAR NUEVO CONTRATO");
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("FECHA INICIO:");

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setText("FECHA FIN:");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setText("Responsable del Mercado:");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Sector");

        tablaPuesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPuesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPuestoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPuesto);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Busqueda:");

        txtBusqueda.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setText("Nro:");

        txtNumeroContrato.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnRegistrar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR CONTRATO");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        comboSector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSectorActionPerformed(evt);
            }
        });

        jDateChooser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jDateChooser1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCerrar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaClientes);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("CLIENTES");

        btnNuevoCliente.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Busqueda:");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoCliente)))
                        .addContainerGap(44, Short.MAX_VALUE))))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addContainerGap())
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtNumeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(comboSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNuevoCliente)
                            .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        getContentPane().add(PanelPrincipal, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         
        try {
            fechaInicioContrato = funcionFecha.getFecha(jDateChooser);
            fechaFinContrato = funcionFecha.getFecha(jDateChooser1);
            
            if(fechaInicioContrato.isBefore(fechaFinContrato)){
                ResponsableAlquiler responsableAlquiler = mercado.getResponsableAlquiler();
                Integer numeroIdentificacionContrato = Integer.parseInt(txtNumeroContrato.getText());

                String nombreSector = comboSector.getSelectedItem().toString();
                Integer numeroPuesto = (Integer)tablaPuesto.getValueAt(tablaPuesto.getSelectedRow(), ModelTablePuesto.NUMERO);
                String clave = tablaClientes.getValueAt(tablaClientes.getSelectedRow(),ModelTableCliente.CUILCUIT).toString();
                
                Sector sectorEncontrado = this.mercado.buscarUnSector(nombreSector);
                Puesto puestoEncontrado = sectorEncontrado.obtenerUnPuesto(numeroPuesto);
                Cliente clienteEncontrado = this.mercado.buscarCliente(clave);
                mercado.verificarContrato(numeroIdentificacionContrato);
                
                Contrato nuevoContrato = new Contrato(fechaInicioContrato, fechaFinContrato, responsableAlquiler, clienteEncontrado, puestoEncontrado, numeroIdentificacionContrato);
                this.mercado.agregarContrato(nuevoContrato);
                JOptionPane.showMessageDialog(null, "CONTRATO REGISTRADO CON EXITO");
             } else {
                JOptionPane.showMessageDialog(null, "LA FECHA DE VENCIMIENTO NO PUEDE SER POSTERIOR A LA FECHA DE EMISION");
            }
        } catch (FechaInvalidaException ex) {
           JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (SectorInexistenteException ex) {
             JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (PuestoInexistenteException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (ClienteInexistenteException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (PuestoOcupadoException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (ContratoExistenteException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Debe seleccionar los elementos de las tablas");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void comboSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSectorActionPerformed
        // TODO add your handling code here:
        
          elementoSeleccionado =  comboSector.getSelectedItem().toString();
        try {
            
            Filtrado.filtrarPorComboBox(elementoSeleccionado, mercado, modeloTablaPuesto);
           
            
        } catch (SectorInexistenteException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } 
        
      
    }//GEN-LAST:event_comboSectorActionPerformed

    private void tablaPuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPuestoMouseClicked
        // TODO add your handling code here:
        
         String puestoSeleccionado = tablaPuesto.getValueAt(tablaPuesto.getSelectedRow(), ModelTablePuesto.NUMERO).toString();
         String sectorSeleccionado = comboSector.getSelectedItem().toString();
      
        try {
        
            Filtrado.ObtenerDetallesDelPuesto(sectorSeleccionado, puestoSeleccionado, mercado);
       
        } catch (SectorInexistenteException ex) {
           JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (PuestoInexistenteException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_tablaPuestoMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
       
         AgregarCliente agregarCliente = new AgregarCliente(mercado,modeloTablaClientes);
         MenuPrincipal.PanelEscritorio.add(agregarCliente);
         Dimension desktopSize =  MenuPrincipal.PanelEscritorio.getSize();
         Dimension FrameSize = agregarCliente.getSize();
         agregarCliente.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);  
         agregarCliente.show();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    public void cargarDatosDelResponsable(){
        
       jTextArea1.setText(mercado.getResponsableAlquiler().toString());
       jTextArea1.setEditable(false);
    }
    
    public void cargarNumeroDeContrato(){
       
       Integer numero = mercado.obtenerCantidadDeContratos() + 1;
        
        txtNumeroContrato.setText(String.valueOf(numero));
        //txtNumeroContrato.setEditable(false);
        txtNumeroContrato.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    public void validarCamposDeTexto(String nombreQuintero, String direccionQuintero,String nombreEmpresa,String direccionEmpresa/*, Integer fila*/){
        
        
            if(nombreQuintero.isEmpty() && direccionQuintero.isEmpty() && nombreEmpresa.isEmpty() && direccionEmpresa.isEmpty()){
            
                 JOptionPane.showMessageDialog(null, "COMPLETE LOS CAMPOS");
            }else{
                
                if(nombreQuintero.isEmpty() && nombreEmpresa.isEmpty() ){
                    JOptionPane.showMessageDialog(null, "El campo NOMBRE esta vacio");
                }
                
                if(direccionQuintero.isEmpty() && direccionEmpresa.isEmpty()){
                     JOptionPane.showMessageDialog(null, "El campo DIRECCION esta vacio");
                }
             
            }
        
    }
    public void verificarFechaDeContrato(){
     if(fechaFinContrato.isBefore(fechaInicioContrato)){
                JOptionPane.showMessageDialog(null, "La Fecha de Fin de Contrato no puede ser Anterior a la Fecha de Inicio del mismo");
            
            }
}


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboSector;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaPuesto;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedaClientes;
    private javax.swing.JTextField txtNumeroContrato;
    // End of variables declaration//GEN-END:variables






}
