/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import mercadoabasto.mercado.Mercado;
import mercadoabasto.mercado.Sector;
import mercadoabasto.exepciones.SectorExistenteException;
import mercadoabasto.exepciones.LimiteSectoresException;
/**
 *
 * @author Usuario
 */
public class AgregarSector extends javax.swing.JInternalFrame {

    private Mercado mercado;
    /**
     * Creates new form AgregarSector
     */
    public AgregarSector(Mercado mercado) {
        super("Agregar sector");
        initComponents();
        setResizable(false);
        this.mercado = mercado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreSectorLabel = new javax.swing.JLabel();
        limitePuestosLabel = new javax.swing.JLabel();
        precioMetroCuadadoLabel = new javax.swing.JLabel();
        porcentajeGeneralLabel = new javax.swing.JLabel();
        porcentajeTechoLabel = new javax.swing.JLabel();
        porcentajeCamaraLabel = new javax.swing.JLabel();
        nombreSectorTextField = new javax.swing.JTextField();
        limitePuestosTextField = new javax.swing.JTextField();
        precioMetroCuadradoTextField = new javax.swing.JTextField();
        porcentajeGeneralTextField = new javax.swing.JTextField();
        porcentajeTechoTextField = new javax.swing.JTextField();
        porcentajeCamaraTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        nombreSectorLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        nombreSectorLabel.setText("Nombre del sector:");

        limitePuestosLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        limitePuestosLabel.setText("Cantidad de puestos:");

        precioMetroCuadadoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        precioMetroCuadadoLabel.setText("Precio por metro cuadrado: $");

        porcentajeGeneralLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        porcentajeGeneralLabel.setText("Caracteristicas extras:");

        porcentajeTechoLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        porcentajeTechoLabel.setText("Techo:");

        porcentajeCamaraLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        porcentajeCamaraLabel.setText("Camara frigorifica:");

        guardarButton.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("%");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("%");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("%");

        jButton1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Porcentaje de intereses agregados por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(limitePuestosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limitePuestosTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreSectorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreSectorTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(precioMetroCuadadoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precioMetroCuadradoTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(porcentajeCamaraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcentajeCamaraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(porcentajeGeneralLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(porcentajeGeneralTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(guardarButton))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(porcentajeTechoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(porcentajeTechoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jButton1)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreSectorLabel)
                    .addComponent(nombreSectorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitePuestosLabel)
                    .addComponent(limitePuestosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioMetroCuadadoLabel)
                    .addComponent(precioMetroCuadradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentajeGeneralTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(porcentajeTechoLabel)
                    .addComponent(porcentajeTechoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(porcentajeGeneralLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(porcentajeCamaraLabel)
                    .addComponent(porcentajeCamaraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed

        try{
            if(controlarCamposVacios()){
                if(controlarNumerosIngresados()){
                    String nombreSector = nombreSectorTextField.getText().toUpperCase();
                    Integer limitePuestos = Integer.parseInt(limitePuestosTextField.getText());
                    BigDecimal precioMetroCuadrado = new BigDecimal(Integer.parseInt(precioMetroCuadradoTextField.getText()));
                    Integer porcentajeGeneral = Integer.parseInt(porcentajeGeneralTextField.getText());
                    Integer porcentajeTecho = Integer.parseInt(porcentajeTechoTextField.getText());
                    Integer porcentajeCamara = Integer.parseInt(porcentajeCamaraTextField.getText());

                    Sector nuevoSector = new Sector(nombreSector, limitePuestos, precioMetroCuadrado, porcentajeGeneral, porcentajeTecho, porcentajeCamara);
                    this.mercado.agregarSector(nuevoSector);

                    MenuPrincipal.modeloCombo.addElement(nuevoSector.getNombreSector());
                    JOptionPane.showMessageDialog(null,"SECTOR AGREGADO CORRECTAMENTE");

                    limpiarCampos();
                }
            }
        } catch (SectorExistenteException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (LimiteSectoresException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Solo se permiten letras en el nombre del sector");
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel limitePuestosLabel;
    private javax.swing.JTextField limitePuestosTextField;
    private javax.swing.JLabel nombreSectorLabel;
    private javax.swing.JTextField nombreSectorTextField;
    private javax.swing.JLabel porcentajeCamaraLabel;
    private javax.swing.JTextField porcentajeCamaraTextField;
    private javax.swing.JLabel porcentajeGeneralLabel;
    private javax.swing.JTextField porcentajeGeneralTextField;
    private javax.swing.JLabel porcentajeTechoLabel;
    private javax.swing.JTextField porcentajeTechoTextField;
    private javax.swing.JLabel precioMetroCuadadoLabel;
    private javax.swing.JTextField precioMetroCuadradoTextField;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos(){
        nombreSectorTextField.setText(null);
        limitePuestosTextField.setText(null);
        precioMetroCuadradoTextField.setText(null);
        porcentajeGeneralTextField.setText(null);
        porcentajeTechoTextField.setText(null);
        porcentajeCamaraTextField.setText(null);
    }
    
    private Boolean controlarCamposVacios(){
        //controla que haya texto en los campos, cambiando el cartel mostrado dependiendo del dato faltante
        
        if(nombreSectorTextField.getText().isEmpty() && limitePuestosTextField.getText().isEmpty() && precioMetroCuadradoTextField.getText().isEmpty() && porcentajeGeneralTextField.getText().isEmpty() && porcentajeTechoTextField.getText().isEmpty() && porcentajeCamaraTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Los campos no pueden estar vacios");
        } else {        
            if(nombreSectorTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El nombre del sector no puede estar vacio");
            }
            if(limitePuestosTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "La cantidad de puestos no puede estar vacia");
            }
            if(precioMetroCuadradoTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El precio por metro cuadrado no puede estar vacio");
            }
            if(porcentajeGeneralTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El porcentaje general no puede estar vacio");
            }
            if(porcentajeTechoTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El porcentaje por el techo no puede estar vacio");
            }
            if(porcentajeCamaraTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "El porcentaje por camara frigorifica no puede estar vacio");
            }
        }
        if(nombreSectorTextField.getText().isEmpty() || limitePuestosTextField.getText().isEmpty() || precioMetroCuadradoTextField.getText().isEmpty() || porcentajeGeneralTextField.getText().isEmpty() || porcentajeTechoTextField.getText().isEmpty() || porcentajeCamaraTextField.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    private Boolean controlarNumerosIngresados(){
        if(Integer.parseInt(limitePuestosTextField.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El limite de puestos debe ser mayor a 0");
        }
        if(Integer.parseInt(precioMetroCuadradoTextField.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El precio por metro cuadrado debe ser mayor a 0");
        }
        if(Integer.parseInt(porcentajeGeneralTextField.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El porcentaje general debe ser mayor a 0");
        }
        if(Integer.parseInt(porcentajeTechoTextField.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El porcentaje por el techo debe ser mayor a 0");
        }
        if(Integer.parseInt(porcentajeCamaraTextField.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El porcentaje por camara frigorifica debe ser mayor a 0");
        }
        if(Integer.parseInt(limitePuestosTextField.getText())==0 || Integer.parseInt(precioMetroCuadradoTextField.getText())==0 || Integer.parseInt(porcentajeGeneralTextField.getText())==0 || Integer.parseInt(porcentajeTechoTextField.getText())==0 || Integer.parseInt(porcentajeCamaraTextField.getText())==0){
                return false;
        }
        return true;
    }
}
