/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fecha.FuncionFecha;
import java.awt.Color;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import mercadoabasto.exepciones.FechaInvalidaException;
import mercadoabasto.exepciones.LecturaExistenteExeption;
import mercadoabasto.exepciones.MedidorInexistenteException;
import mercadoabasto.mercado.Lectura;
import mercadoabasto.mercado.Medidor;
import mercadoabasto.mercado.Mercado;

/**
 *
 * @author usuario
 */
public class AgregarLectura extends javax.swing.JInternalFrame {

    private Mercado mercado;
    private FuncionFecha funcionFecha;
    private Medidor medidorEncontrado = null;
    
    public AgregarLectura(Mercado mercado) {
        initComponents();
        this.mercado = mercado;
        configuracionCampos();
        funcionFecha = new FuncionFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscador = new javax.swing.JTextField();
        LabelResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtConsumo = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        btnAsignarLectura = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnVerLecturas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setTitle("Agregar lectura");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnBuscar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        LabelResultado.setBackground(new java.awt.Color(255, 255, 255));
        LabelResultado.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        LabelResultado.setForeground(new java.awt.Color(0, 204, 0));
        LabelResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Buscar medidor Nro:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("Fecha de Lectura:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("Consumo:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("Precio:  $");

        jDateChooser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnAsignarLectura.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAsignarLectura.setText("Asignar Lectura");
        btnAsignarLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarLecturaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("kw");

        btnVerLecturas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnVerLecturas.setText("Ver Lecturas");
        btnVerLecturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLecturasActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAsignarLectura))
                        .addGap(227, 227, 227)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(161, 161, 161)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnVerLecturas))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LabelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerLecturas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))))
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnCerrar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsignarLectura)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       LabelResultado.setText("");
        try{
            if(!txtBuscador.getText().isEmpty()){
                if(Integer.parseInt(txtBuscador.getText())!=0){
                        Integer numeroMedidor = Integer.parseInt(txtBuscador.getText());
                        this.medidorEncontrado = this.mercado.buscarMedidorMercado(numeroMedidor);
                        LabelResultado.setHorizontalAlignment(SwingConstants.CENTER);
                        LabelResultado.setText("MEDIDOR ENCONTRADO");
                        txtConsumo.setEditable(true);
                        txtPrecio.setEditable(true);
                        jDateChooser.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "El n\u00FAmero de medidor debe ser mayor a 0");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El n\u00FAmero de medidor no puede estar vacio");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Solo se pueden escribir n\u00FAmeros en el campo para buscar medidor");
        } catch (MedidorInexistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            txtBuscador.setText(null);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAsignarLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarLecturaActionPerformed
        // TODO add your handling code here:
        try{
            if(this.medidorEncontrado!=null){
                if(controlarCamposVacios()){
                    if(Integer.parseInt(txtPrecio.getText())!=0){
                        Integer numeroMedidor = Integer.parseInt(txtBuscador.getText());
                        BigDecimal precio = new BigDecimal(txtPrecio.getText());
                        BigDecimal consumo = new BigDecimal(txtConsumo.getText());
                        LocalDate periodo = funcionFecha.getFecha(jDateChooser);
                        Medidor medidorEncontrado = this.mercado.buscarMedidorMercado(numeroMedidor);
                        Lectura nuevaLectura = new Lectura(periodo, consumo, precio);
                        medidorEncontrado.agregarLectura(nuevaLectura);
                        JOptionPane.showMessageDialog(null, "Lectura asignada al medidor n\u00FAmero: "+ numeroMedidor);
                        configuracionCampos();
                    } else {
                        JOptionPane.showMessageDialog(null, "El campor de precio por kilowatt no puede contener valor 0");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe buscar el medidor antes de poder asignar una lectura");
            }
        } catch (MedidorInexistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (FechaInvalidaException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (LecturaExistenteExeption ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Complete los campos con los N\u00DAMEROS correspondientes");
        }
      
    }//GEN-LAST:event_btnAsignarLecturaActionPerformed

    private void btnVerLecturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLecturasActionPerformed
        if(this.medidorEncontrado == null){
            JOptionPane.showMessageDialog(null, "Debe buscar el medidor antes de poder ver sus lecturas");
        }else{
          ListaLectura listaLectura = new ListaLectura(this.medidorEncontrado);
          listaLectura.setVisible(true);
        }
    }//GEN-LAST:event_btnVerLecturasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    public void configuracionCampos(){
        txtBuscador.setText(null);
        txtPrecio.setText(null);
        txtConsumo.setText(null);
        LabelResultado.setText(null);
        txtConsumo.setEditable(false);
        txtPrecio.setEditable(false);
        jDateChooser.setEnabled(false);
    }
    
    public Boolean controlarCamposVacios(){
        if(txtConsumo.getText().isEmpty() && txtPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El consumo y el precio por kilowatt no pueden estar vac\u00EDos");
        } else {
            if(txtConsumo.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"El campo CONSUMO no puede estar vac\u00EDo");
            }
            if(txtPrecio.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"El campo PRECIO no puede estar vac\u00EDo");
            }
        }
        if(txtConsumo.getText().isEmpty() || txtPrecio.getText().isEmpty()){
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelResultado;
    private javax.swing.JButton btnAsignarLectura;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnVerLecturas;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtBuscador;
    private javax.swing.JTextField txtConsumo;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
