/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Filtrado.Filtrado;
import ModeloTablaSector.CeldasRenderTableSector;
import ModeloTablaSector.ModelTableSector;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import mercadoabasto.exepciones.LimitePuestosException;
import mercadoabasto.exepciones.MedidorOcupadoException;
import mercadoabasto.exepciones.PuestoExistenteException;
import mercadoabasto.exepciones.SectorInexistenteException;
import mercadoabasto.mercado.Medidor;
import mercadoabasto.mercado.Mercado;
import mercadoabasto.mercado.Puesto;
import mercadoabasto.mercado.Sector;

/**
 *
 * @author Daniel Juarez
 */
public class AgregarPuesto extends javax.swing.JInternalFrame {

   private Mercado mercado;
   private ModelTableSector modeloTablaSectores;
   private TableRowSorter trsFiltro;
   
    public AgregarPuesto(Mercado mercado) {
        initComponents();
        setResizable(false);
        this.mercado = mercado;
        configuracionCheckBox();
    
        this.modeloTablaSectores = new ModelTableSector();
        tablaSectores.setModel(modeloTablaSectores);
        tablaSectores.setDefaultRenderer(Object.class, new CeldasRenderTableSector());
        trsFiltro = new TableRowSorter(tablaSectores.getModel());
        tablaSectores.setRowSorter(trsFiltro);
        
        //Evento de Teclado - Busqueda Dinamica
        txtBusqueda.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyReleased(KeyEvent e) {
                Filtrado.filtrarPorNombreSector(txtBusqueda, trsFiltro);
            }
            
        });
        
        modeloTablaSectores.cargarDatosDelSector(this.mercado.getSectores());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalPuesto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroPuesto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        txtLargo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CheckTecho = new javax.swing.JCheckBox();
        CheckCamaraRefrigerante = new javax.swing.JCheckBox();
        CheckBanio = new javax.swing.JCheckBox();
        CheckAguaPotable = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        txtMedidor = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSectores = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        setTitle("AGREGAR PUESTO");

        PanelPrincipalPuesto.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Caracteristica del Puesto:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Nro:");

        txtNumeroPuesto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Dimenciones:");

        txtAncho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txtLargo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("X");

        CheckTecho.setBackground(new java.awt.Color(204, 204, 255));
        CheckTecho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        CheckTecho.setText("Techo");

        CheckCamaraRefrigerante.setBackground(new java.awt.Color(204, 204, 255));
        CheckCamaraRefrigerante.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        CheckCamaraRefrigerante.setText("Camara Refrigerante");

        CheckBanio.setBackground(new java.awt.Color(204, 204, 255));
        CheckBanio.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        CheckBanio.setText("Banio");

        CheckAguaPotable.setBackground(new java.awt.Color(204, 204, 255));
        CheckAguaPotable.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        CheckAguaPotable.setText("Agua Potable");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Medidor:");

        txtMedidor.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("m");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("m");

        tablaSectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSectores);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Sectores:");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Busqueda:");

        txtBusqueda.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Sector no disponible");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Sector disponible");

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        btnCerrar.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalPuestoLayout = new javax.swing.GroupLayout(PanelPrincipalPuesto);
        PanelPrincipalPuesto.setLayout(PanelPrincipalPuestoLayout);
        PanelPrincipalPuestoLayout.setHorizontalGroup(
            PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckAguaPotable)
                                    .addComponent(CheckBanio)
                                    .addComponent(CheckTecho)
                                    .addComponent(CheckCamaraRefrigerante))
                                .addGap(133, 133, 133)
                                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                                .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1)
                            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))
                            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                                .addGap(458, 458, 458)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumeroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(216, 216, 216)
                        .addComponent(btnCerrar)))
                .addContainerGap())
        );
        PanelPrincipalPuestoLayout.setVerticalGroup(
            PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addComponent(CheckTecho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckCamaraRefrigerante, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBanio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CheckAguaPotable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumeroPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(PanelPrincipalPuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnCerrar))
                    .addGroup(PanelPrincipalPuestoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(PanelPrincipalPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            if(controlarCamposVacios()){
                if(controlarNumerosIngresados()){
            
                    Double ancho = Double.parseDouble(txtAncho.getText());
                    Double largo = Double.parseDouble(txtLargo.getText());
                    BigDecimal dimension = new BigDecimal(ancho*largo);
                    Integer numeroDeMedidor = Integer.parseInt(txtMedidor.getText());
                    Integer numeroPuesto = Integer.parseInt(txtNumeroPuesto.getText()); 
                    String nombreSector = (String) tablaSectores.getValueAt(tablaSectores.getSelectedRow(), ModelTableSector.NOMBRE);

                    mercado.comprobarMedidor(numeroDeMedidor); // aca compruebo

                    Sector sectorEncontrado = this.mercado.buscarUnSector(nombreSector);
                    Medidor numerMedidor = new Medidor(numeroDeMedidor);

                    if(CheckTecho.isSelected() == false && CheckCamaraRefrigerante.isSelected() == false){
                       JOptionPane.showMessageDialog(null, "Seleccione al menos una casilla");
                    }else{ 
                        if(CheckTecho.isSelected() == true && CheckCamaraRefrigerante.isSelected() == true && CheckBanio.isSelected() == true && CheckAguaPotable.isSelected() == true){
                            Puesto nuevoPuesto = new Puesto(numeroPuesto, true, true, true, true, dimension,numerMedidor,sectorEncontrado);
                            sectorEncontrado.agregarPuesto(nuevoPuesto);
                            JOptionPane.showMessageDialog(null, "PUESTO AGREGADO");
                        }else{
                            if(CheckTecho.isSelected() == true ){
                                Puesto nuevoPuesto = new Puesto(numeroPuesto, true, false, true, true, dimension,numerMedidor,sectorEncontrado);
                                sectorEncontrado.agregarPuesto(nuevoPuesto);
                                JOptionPane.showMessageDialog(null, "PUESTO AGREGADO");
                            }else{
                                Puesto nuevoPuesto = new Puesto(numeroPuesto, false, true, true, true, dimension,numerMedidor,sectorEncontrado);
                                sectorEncontrado.agregarPuesto(nuevoPuesto);
                                JOptionPane.showMessageDialog(null, "PUESTO AGREGADO");
                            }
                        }
                    }
                    contador();
                }
            }
        } catch (SectorInexistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (MedidorOcupadoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (PuestoExistenteException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (LimitePuestosException ex) {
          JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null,"Seleccione un SECTOR de la tabla" );
        }catch(NumberFormatException ex ){
           JOptionPane.showMessageDialog(null, "Solo se permiten numeros en los campos");
        }
           
       
        modeloTablaSectores.limpiarTabla();
        modeloTablaSectores.cargarDatosDelSector(mercado.getSectores());      
   
   
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    public void configuracionCheckBox(){
        CheckAguaPotable.setSelected(true);
        CheckAguaPotable.setEnabled(false);
        CheckBanio.setSelected(true);
        CheckBanio.setEnabled(false);
    }
    
    public void contador(){
    
        Integer numeroPuesto = Integer.parseInt(txtNumeroPuesto.getText());
        txtNumeroPuesto.setText(String.valueOf(numeroPuesto+1));
        
        Integer numeroMedidor = Integer.parseInt(txtMedidor.getText());
        txtMedidor.setText(String.valueOf(numeroMedidor+1));
    }
    
    public boolean controlarCamposVacios(){
        if(txtAncho.getText().isEmpty() && txtLargo.getText().isEmpty() && txtMedidor.getText().isEmpty() && txtNumeroPuesto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "COMPLETE LOS CAMPOS");
        }else{
            if(txtAncho.getText().isEmpty() || txtLargo.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null, "Faltan datos en el campo DIMENSIONES");
            }
            if(txtMedidor.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "EL campo MEDIDOR esta vacio");
            }
            if(txtNumeroPuesto.getText().isEmpty()){
               JOptionPane.showMessageDialog(null, "EL campo NRO esta vacio");
            }
        }
        if(txtAncho.getText().isEmpty() || txtLargo.getText().isEmpty() || txtMedidor.getText().isEmpty() || txtNumeroPuesto.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    public boolean controlarNumerosIngresados(){
    
        if(Double.parseDouble(txtAncho.getText()) == 0 ||Double.parseDouble(txtLargo.getText()) == 0 ){
            JOptionPane.showMessageDialog(null, "El ancho y/o largo del puesto debe ser mayor a 0");
        }
       
        if(Integer.parseInt(txtMedidor.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El numero de medidor debe ser mayor a 0");
        }
     
        if(Integer.parseInt(txtNumeroPuesto.getText()) == 0){
            JOptionPane.showMessageDialog(null, "El numero del puesto debe ser mayor a 0");
        }
        if(Double.parseDouble(txtAncho.getText()) == 0 ||Double.parseDouble(txtLargo.getText()) == 0 || Integer.parseInt(txtMedidor.getText())==0 || Integer.parseInt(txtNumeroPuesto.getText())==0){
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckAguaPotable;
    private javax.swing.JCheckBox CheckBanio;
    private javax.swing.JCheckBox CheckCamaraRefrigerante;
    private javax.swing.JCheckBox CheckTecho;
    private javax.swing.JPanel PanelPrincipalPuesto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSectores;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtLargo;
    private javax.swing.JTextField txtMedidor;
    private javax.swing.JTextField txtNumeroPuesto;
    // End of variables declaration//GEN-END:variables

}
