/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ModeloTablaFactura.CeldasRenderTableFactura;
import ModeloTablaFactura.ModelTableFactura;
import mercadoabasto.mercado.*;
import Fecha.FuncionFecha;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mercadoabasto.conceptosCobro.Factura;
import mercadoabasto.exepciones.FacturaInexistenteExeption;
import mercadoabasto.exepciones.FechaInvalidaException;

/**
 *
 * @author Usuario
 */
public class BuscarFactura extends javax.swing.JInternalFrame {

    private Mercado mercado;
    private ModelTableFactura modeloTablaFacturas;
    private FuncionFecha fechaTool;
    private LocalDate fechaEmisionFactura;
    private LocalDate fechaVencimientoFactura;
    private VerFactura verFactura = null;
    
    public BuscarFactura(Mercado mercado) {
        super("Buscar Factura");
        initComponents();
        fechaTool = new FuncionFecha();
        this.mercado = mercado;
        modeloTablaFacturas = new ModelTableFactura();
        tablaFacturas.setModel(modeloTablaFacturas);
        tablaFacturas.setDefaultRenderer(Object.class, new CeldasRenderTableFactura());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();
        dcFechaEmision = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarFacturas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblRendicion = new javax.swing.JLabel();
        txtFacturasVencidas = new javax.swing.JTextField();
        txtFacturasVigentes = new javax.swing.JTextField();
        txtFacturasPorVencer = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFacturas);

        dcFechaVencimiento.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        dcFechaEmision.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setText("Desde:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Hasta:");

        btnBuscarFacturas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnBuscarFacturas.setText("Buscar facturas");
        btnBuscarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturasActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 78, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rendicion entre fechas seleccionadas");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblRendicion.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblRendicion.setForeground(new java.awt.Color(255, 255, 255));
        lblRendicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRendicion.setText("0");
        lblRendicion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRendicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRendicion))
        );

        txtFacturasVencidas.setEditable(false);
        txtFacturasVencidas.setBackground(new java.awt.Color(255, 102, 102));
        txtFacturasVencidas.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFacturasVencidas.setText("Factura vencida");
        txtFacturasVencidas.setBorder(null);
        txtFacturasVencidas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFacturasVencidas.setEnabled(false);

        txtFacturasVigentes.setEditable(false);
        txtFacturasVigentes.setBackground(new java.awt.Color(102, 255, 102));
        txtFacturasVigentes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFacturasVigentes.setText("Factura vigente");
        txtFacturasVigentes.setBorder(null);
        txtFacturasVigentes.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFacturasVigentes.setEnabled(false);

        txtFacturasPorVencer.setEditable(false);
        txtFacturasPorVencer.setBackground(new java.awt.Color(255, 200, 0));
        txtFacturasPorVencer.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtFacturasPorVencer.setText("Factura por vencer");
        txtFacturasPorVencer.setBorder(null);
        txtFacturasPorVencer.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFacturasPorVencer.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFacturasVencidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturasVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFacturasPorVencer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnCerrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFechaEmision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(dcFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFacturasVencidas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFacturasVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFacturasPorVencer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCerrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturasActionPerformed
        try {
            modeloTablaFacturas.limpiarTabla();
            fechaEmisionFactura = fechaTool.getFecha(dcFechaEmision);
            fechaVencimientoFactura = fechaTool.getFecha(dcFechaVencimiento);
            ArrayList<Factura> listaDeFacturas = this.mercado.getFacturero().buscarUnRagoDeFacturas(fechaEmisionFactura, fechaVencimientoFactura);
            modeloTablaFacturas.cargarDatosDeFacturas(listaDeFacturas);
            lblRendicion.setText("$ "+this.mercado.getFacturero().rendicionMensual(fechaEmisionFactura, fechaVencimientoFactura).toString());
            txtFacturasVencidas.setText("Facturas vencidas: "+this.mercado.getFacturero().cantidadDeFacturasVencidas(listaDeFacturas));
            txtFacturasVigentes.setText("Facturas vigentes: "+this.mercado.getFacturero().cantidadDeFacturasVigentes(listaDeFacturas));
            txtFacturasPorVencer.setText("Facturas por vencer: "+this.mercado.getFacturero().cantidadDeFacturasPorVencer(listaDeFacturas));
        
        } catch (FechaInvalidaException ex) {
            JOptionPane.showMessageDialog(null, "La fecha introducida es invalida");
        } catch (FacturaInexistenteExeption ex) {
            JOptionPane.showMessageDialog(null, "No se encontraron facturas dentro del rango especificado");
        }
    }//GEN-LAST:event_btnBuscarFacturasActionPerformed

    private void tablaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFacturasMouseClicked
        if(verFactura == null || verFactura.isClosed()){
            try {
                Integer numeroFacturaSeleccionada = (Integer) tablaFacturas.getValueAt(tablaFacturas.getSelectedRow(), ModelTableFactura.NUMEROFACTURA);
                Factura facturaEncontrada = this.mercado.getFacturero().buscarUnaFactura(numeroFacturaSeleccionada);
                verFactura = new VerFactura(this.mercado, facturaEncontrada);
                MenuPrincipal.PanelEscritorio.add(verFactura);
                Dimension desktopSize =  MenuPrincipal.PanelEscritorio.getSize();
                Dimension FrameSize = verFactura.getSize();
                verFactura.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);  
                verFactura.show();
            } catch (FacturaInexistenteExeption ex) {
                    JOptionPane.showMessageDialog(null, "La factura seleccionada no existe");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ya se encuentra activa una ventana para ver factura");
        }
    }//GEN-LAST:event_tablaFacturasMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFacturas;
    private javax.swing.JButton btnCerrar;
    private com.toedter.calendar.JDateChooser dcFechaEmision;
    private com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRendicion;
    private javax.swing.JTable tablaFacturas;
    private javax.swing.JTextField txtFacturasPorVencer;
    private javax.swing.JTextField txtFacturasVencidas;
    private javax.swing.JTextField txtFacturasVigentes;
    // End of variables declaration//GEN-END:variables
}
