
package GUI;

import Filtrado.Filtrado;
import static GUI.MenuPrincipal.PanelEscritorio;
import ModeloTablaCliente.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import mercadoabasto.exepciones.ClienteInexistenteException;
import mercadoabasto.mercado.Mercado;
import java.awt.Dimension;
import mercadoabasto.clientes.Cliente;

/**
 *
 * @author Usuario
 */
public class ListarClientes extends javax.swing.JInternalFrame {

    private Mercado mercado;
    private ModelTableCliente modeloTablaClientes;
    private TableRowSorter trsFiltro;
    private VerContratosPuestosDelCliente verContratosPuestosDelCliente = null;
    private ListarFacturasCliente listarFacturasCliente;
    private DetallesDelCliente detallesDelCliente;
    private Cliente clienteSeleccionado = null;
    /**
     * Creates new form ListarClientes
     */
    public ListarClientes(Mercado mercado) {
        initComponents();
        this.mercado=mercado;
        
        //Modelo Tabla Clientes
        modeloTablaClientes = new ModelTableCliente();
        tablaClientes.setModel(modeloTablaClientes);
        trsFiltro = new TableRowSorter(tablaClientes.getModel());
        tablaClientes.setRowSorter(trsFiltro);
        tablaClientes.setDefaultRenderer(Object.class , new CeldasRenderTableCliente());
       
        //Listener para filtrar tabla de clientes
        txtBusquedaClientes.addKeyListener(new KeyAdapter(){
                @Override
                public void keyReleased(final KeyEvent e){
                    Filtrado.filtrarClientesPorCuilCuit(txtBusquedaClientes, trsFiltro);
                    clienteSeleccionado = null;
                }
            });
        
        modeloTablaClientes.limpiarTabla();
        modeloTablaClientes.cargarDatosDeClientes(this.mercado.getClientes());
        lblCantidadClientes.setText("Cantidad de clientes: "+this.mercado.obtenerCantidadClientes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusquedaClientes = new javax.swing.JTextField();
        btnDetallesContratosPuestos = new javax.swing.JButton();
        btnFacturasCliente = new javax.swing.JButton();
        btnDetallesCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCantidadClientes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setText("Buscar:");

        btnDetallesContratosPuestos.setText("Ver contratos y puestos del cliente");
        btnDetallesContratosPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesContratosPuestosActionPerformed(evt);
            }
        });

        btnFacturasCliente.setText("Ver facturas del cliente");
        btnFacturasCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasClienteActionPerformed(evt);
            }
        });

        btnDetallesCliente.setText("Ver detalles del cliente");
        btnDetallesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesClienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 78, 204));

        lblCantidadClientes.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCantidadClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadClientes.setText("Cantidad de clientes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCantidadClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCantidadClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetallesContratosPuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(btnFacturasCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDetallesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetallesContratosPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFacturasCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetallesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDetallesContratosPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesContratosPuestosActionPerformed
        if(clienteSeleccionado!=null){
            if(verContratosPuestosDelCliente == null || verContratosPuestosDelCliente.isClosed()){
                verContratosPuestosDelCliente = new VerContratosPuestosDelCliente(mercado, clienteSeleccionado);
                PanelEscritorio.add(verContratosPuestosDelCliente);
                Dimension desktopSize = PanelEscritorio.getSize();
                Dimension FrameSize = verContratosPuestosDelCliente.getSize();
                verContratosPuestosDelCliente.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);  
                verContratosPuestosDelCliente.show();
            }else{
                 JOptionPane.showMessageDialog(null, "La Ventana Se Encuentra Abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente para poder ver sus contratos");
        }
    }//GEN-LAST:event_btnDetallesContratosPuestosActionPerformed

    private void btnFacturasClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasClienteActionPerformed
        if(clienteSeleccionado!=null){
            if(listarFacturasCliente == null || listarFacturasCliente.isClosed()){
                listarFacturasCliente = new ListarFacturasCliente(mercado, clienteSeleccionado);
                PanelEscritorio.add(listarFacturasCliente);
                Dimension desktopSize = PanelEscritorio.getSize();
                Dimension FrameSize = listarFacturasCliente.getSize();
                listarFacturasCliente.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);  
                listarFacturasCliente.show();
            }else{
                 JOptionPane.showMessageDialog(null, "La Ventana Se Encuentra Abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente para poder ver sus facturas");
        }
    }//GEN-LAST:event_btnFacturasClienteActionPerformed

    private void btnDetallesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesClienteActionPerformed
        if(clienteSeleccionado != null){
            if(detallesDelCliente == null || detallesDelCliente.isClosed()){
                detallesDelCliente = new DetallesDelCliente(this.mercado, modeloTablaClientes, clienteSeleccionado);
                PanelEscritorio.add(detallesDelCliente);
                Dimension desktopSize = PanelEscritorio.getSize();
                Dimension FrameSize = detallesDelCliente.getSize();
                detallesDelCliente.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);  
                detallesDelCliente.show();
            }else{
                 JOptionPane.showMessageDialog(null, "La Ventana Se Encuentra Abierta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cliente para poder ver sus detalles");
        }
    }//GEN-LAST:event_btnDetallesClienteActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        try {
            String seleccion = tablaClientes.getValueAt(tablaClientes.getSelectedRow(),ModelTableCliente.CUILCUIT).toString();
            clienteSeleccionado = this.mercado.buscarCliente(seleccion);
        } catch (ClienteInexistenteException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_tablaClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetallesCliente;
    private javax.swing.JButton btnDetallesContratosPuestos;
    private javax.swing.JButton btnFacturasCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadClientes;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtBusquedaClientes;
    // End of variables declaration//GEN-END:variables
}
