/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;

/**
 *
 * @author Daniel Juarez
 */
public class ServicioTecnico extends javax.swing.JInternalFrame {

    
    public ServicioTecnico() {
        initComponents();
        
        rsscalelabel.RSScaleLabel.setScaleLabel(label, "D:\\Documentos\\ING. INFORMATICA\\2do Año\\Programacion II\\Laboratorio 2020\\mercadoabastobeta\\src\\imagen\\unnamed.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        btnFacebook = new javax.swing.JButton();
        btnYoutebe = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("SERVICIO TECNICO");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/facebook64_NEGRO.png"))); // NOI18N
        btnFacebook.setBorder(null);
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });

        btnYoutebe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_NEGRO.png"))); // NOI18N
        btnYoutebe.setBorder(null);
        btnYoutebe.setContentAreaFilled(false);
        btnYoutebe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoutebeActionPerformed(evt);
            }
        });

        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_NEGRO.png"))); // NOI18N
        btnTwitter.setBorder(null);
        btnTwitter.setContentAreaFilled(false);
        btnTwitter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Desarrolladores: ");

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel3.setText("Juarez Sergio Daniel");

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel4.setText("Romero Nelson Daniel");

        jLabel5.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jLabel5.setText("Salavarria Braian Antonio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnFacebook)
                        .addGap(55, 55, 55)
                        .addComponent(btnYoutebe)
                        .addGap(55, 55, 55)
                        .addComponent(btnTwitter))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacebook)
                    .addComponent(btnYoutebe)
                    .addComponent(btnTwitter))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.facebook.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnYoutebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoutebeActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.youtube.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnYoutebeActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.twitter.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnTwitterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JButton btnYoutebe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
