/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fecha.FuncionFecha;
import ModeloTablaConcepto.CeldasRenderTableConcepto;
import java.awt.Color;
import java.awt.Font;
import mercadoabasto.mercado.Mercado;
import mercadoabasto.conceptosCobro.*;
import javax.swing.table.JTableHeader;
import ModeloTablaConcepto.ModelTableConcepto;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mercadoabasto.clientes.Cliente;
import mercadoabasto.clientes.Empresa;
import mercadoabasto.clientes.Quintero;
import mercadoabasto.exepciones.ConceptoYaAgregadoException;
import mercadoabasto.exepciones.FacturaExistenteExeption;
import mercadoabasto.exepciones.FacturaYaEmitidaException;
import mercadoabasto.exepciones.FechaInvalidaException;
import mercadoabasto.mercado.Contrato;
import mercadoabasto.mercado.Lectura;
import mercadoabasto.mercado.Puesto;
/**
 *
 * @author Usuario
 */
public class VerFactura extends javax.swing.JInternalFrame {

    private Mercado mercado;
    private ModelTableConcepto modeloTablaConceptos;
    private ArrayList<Concepto> conceptosACobrar;
    private Cliente clienteDeLaFactura;
    private Puesto puestoDeLaFactura;
    private LocalDate fechaEmisionFactura;
    private LocalDate fechaVencimientoFactura;
    private FuncionFecha fechaTool;
    private Integer numeroFacturaActual;
    /**
     * Creates new form VerFactura
     */
    
    //Recibe arraylist de concepto y muestra el boton crear factura, carga todos los datos desde el mercado
    //y el arraylist de conceptos recibido como parametro
    public VerFactura(Mercado mercado, Contrato contrato, Lectura lectura) {
        super("Ver factura");
        initComponents();
        this.mercado=mercado;
        this.conceptosACobrar = new ArrayList<Concepto>();
        this.conceptosACobrar.add(lectura);
        this.conceptosACobrar.add(contrato);
        fechaTool = new FuncionFecha();
        btnCrearFactura.setVisible(true);
        configurarEsteticaTabla();
        cargarDatosMercado();
        cargarDatosCliente();
        numeroFacturaActual = obtenerNumeroDeFacturaActual();
        lblNumeroFactura.setText("Factura Nro: "+numeroFacturaActual.toString());
        modeloTablaConceptos.cargarDatosDeConceptos(this.conceptosACobrar);
        tablaConceptos.setDefaultRenderer(Object.class, new CeldasRenderTableConcepto());
        cargarImporteTotal();
    }
    
    //Recibe una factura y oculta el boton crear factura, carga todos los datos desde el mercado
    //y el arraylist de conceptos que se encuentra en la factura
    public VerFactura(Mercado mercado, Factura factura) {
        super("Ver factura");
        initComponents();
        this.mercado=mercado;
        this.conceptosACobrar = factura.getConceptoACobrar();
        fechaTool = new FuncionFecha();
        btnCrearFactura.setVisible(false);
        configurarEsteticaTabla();
        cargarDatosMercado();
        cargarDatosCliente();
        cargarFechas(factura);
        lblNumeroFactura.setText("Factura Nro: "+factura.getNumeroFactura().toString());
        modeloTablaConceptos.cargarDatosDeConceptos(this.conceptosACobrar);
        tablaConceptos.setDefaultRenderer(Object.class, new CeldasRenderTableConcepto());
        cargarImporteTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConceptos = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();
        btnCrearFactura = new javax.swing.JButton();
        lblNombreMercado = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblNumeroTelefono = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        lblDireccionCliente = new javax.swing.JLabel();
        lblClaveUnica = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        lblFechaEmision = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFechaVencimiento = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblImporteTotal = new javax.swing.JLabel();
        dcFechaEmision = new com.toedter.calendar.JDateChooser();
        dcFechaVencimiento = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(35, 34));

        tablaConceptos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaConceptos);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnCrearFactura.setText("Crear Factura");
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        lblNombreMercado.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNombreMercado.setText("Nombre Mercado");

        lblDireccion.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblDireccion.setText("Direccion");

        lblNumeroTelefono.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNumeroTelefono.setText("Numero Telefono");

        lblNombreCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNombreCliente.setText("Nombre Cliente");

        lblDireccionCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblDireccionCliente.setText("Direccion");

        lblClaveUnica.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblClaveUnica.setText("CUIL/CUIT");

        lblRazonSocial.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblRazonSocial.setText("Razon Social mostrar por condicional");

        lblNumeroFactura.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNumeroFactura.setText("Factura Nro:");

        lblFechaEmision.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblFechaEmision.setText("Fecha de emision:");

        jPanel1.setBackground(new java.awt.Color(0, 78, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facturar A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblFechaVencimiento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblFechaVencimiento.setText("Fecha de vencimiento:");

        jPanel2.setBackground(new java.awt.Color(0, 78, 204));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FACTURA");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblImporteTotal.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblImporteTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImporteTotal.setText("Importe total:");

        dcFechaEmision.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        dcFechaVencimiento.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(lblFechaVencimiento)
                        .addGap(6, 6, 6)
                        .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(lblFechaEmision)
                        .addGap(9, 9, 9)
                        .addComponent(dcFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(lblNumeroFactura))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(lblNombreMercado))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(lblDireccion))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(lblNumeroTelefono))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNombreCliente)
                                                .addComponent(lblDireccionCliente)
                                                .addComponent(lblClaveUnica)
                                                .addComponent(lblRazonSocial))))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnCrearFactura)
                                    .addGap(21, 21, 21)
                                    .addComponent(btnCerrar))
                                .addComponent(lblImporteTotal, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(380, 380, 380)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreMercado)
                    .addComponent(lblNumeroFactura))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(lblFechaEmision)
                    .addComponent(dcFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroTelefono)
                    .addComponent(lblFechaVencimiento)
                    .addComponent(dcFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblNombreCliente)
                        .addGap(7, 7, 7)
                        .addComponent(lblDireccionCliente)
                        .addGap(7, 7, 7)
                        .addComponent(lblClaveUnica)
                        .addGap(7, 7, 7)
                        .addComponent(lblRazonSocial))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImporteTotal)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearFactura)
                            .addComponent(btnCerrar))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        modeloTablaConceptos.limpiarTabla();
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
        try {
            int opcion = JOptionPane.showConfirmDialog(this, "¿DESEA CREAR LA FACTURA?","Confirmar",JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE);
            
            if(opcion == JOptionPane.YES_OPTION ){
                fechaEmisionFactura = fechaTool.getFecha(dcFechaEmision);
                fechaVencimientoFactura = fechaTool.getFecha(dcFechaVencimiento);
                
                if(fechaEmisionFactura.isBefore(fechaVencimientoFactura)){
                    Factura facturaCreada = new Factura(clienteDeLaFactura, puestoDeLaFactura, numeroFacturaActual,fechaEmisionFactura, fechaVencimientoFactura);
                    for (Concepto concepto : conceptosACobrar) {
                        facturaCreada.agregarConceptoACobrar(concepto);
                    }
                    this.mercado.getFacturero().agregarFactura(facturaCreada);
                    JOptionPane.showMessageDialog(null, "FACTURA AGREGADA CON EXITO");
                } else {
                    JOptionPane.showMessageDialog(null, "LA FECHA DE VENCIMIENTO NO PUEDE SER POSTERIOR A LA FECHA DE EMISION");
                }
            }
        } catch (FechaInvalidaException ex) {
            JOptionPane.showMessageDialog(null, "Las fechas ingresadas son invalidas");
        } catch (FacturaExistenteExeption ex) {
            JOptionPane.showMessageDialog(null, "La factura ya existe");
        } catch (ConceptoYaAgregadoException ex) {
            JOptionPane.showMessageDialog(null, "El concepto ya fue agregado");
        } catch (FacturaYaEmitidaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnCrearFacturaActionPerformed

    private void cargarDatosMercado(){
        lblNombreMercado.setText(this.mercado.getNombre());
        lblDireccion.setText(this.mercado.getDireccion());
        lblNumeroTelefono.setText(this.mercado.getNumeroTelefono().getNumeroTelefono());
    }
    
    private void cargarDatosCliente(){
        for (Concepto concepto : this.conceptosACobrar) {
            if(concepto instanceof Contrato){
                Contrato contrato = (Contrato) concepto;
                clienteDeLaFactura = contrato.getCliente();
                puestoDeLaFactura = contrato.getPuesto();
                lblNombreCliente.setText(contrato.getCliente().getNombre());
                lblDireccionCliente.setText(contrato.getCliente().getDireccion());
                if(contrato.getCliente() instanceof Quintero){
                    Quintero quintero = (Quintero) contrato.getCliente();
                    lblClaveUnica.setText(quintero.getCuil().getNumeroClaveUnicaIdentificacion());
                    lblRazonSocial.setVisible(false);
                }
                if(contrato.getCliente() instanceof Empresa){
                    Empresa empresa = (Empresa) contrato.getCliente();
                    lblClaveUnica.setText(empresa.getCuit().getNumeroClaveUnicaIdentificacion());
                    lblRazonSocial.setText(empresa.getRazonSocial());
                }
            }
        }
    }
    
    private int obtenerNumeroDeFacturaActual(){
        return this.mercado.getFacturero().obtenerCantidadDeFacturas()+1;
    }
    
    private void cargarImporteTotal(){
        BigDecimal suma = new BigDecimal(0);
        for (Concepto concepto : this.conceptosACobrar) {
            suma = suma.add(concepto.getImporte());
        }
        lblImporteTotal.setText("Importe total: $"+suma.toString());
    }
    
    
    private void cargarFechas(Factura factura){
        
        this.dcFechaEmision.setVisible(false);
        this.dcFechaVencimiento.setVisible(false);
        lblFechaEmision.setText("Fecha de emision: "+factura.getFechaEmision().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
        lblFechaVencimiento.setText("Fecha de vencimiento: "+factura.getFechaEVencimientoFactura().format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
    }
    
    private void configurarEsteticaTabla(){
        modeloTablaConceptos = new ModelTableConcepto();
        tablaConceptos.setModel(modeloTablaConceptos);
        JTableHeader header = tablaConceptos.getTableHeader();
        header.setBackground(new Color(0,78,204));
        header.setForeground(Color.white);
        header.setFont(new Font("Calibri", Font.BOLD, 14));
        tablaConceptos.setTableHeader(header);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCrearFactura;
    private com.toedter.calendar.JDateChooser dcFechaEmision;
    private com.toedter.calendar.JDateChooser dcFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClaveUnica;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionCliente;
    private javax.swing.JLabel lblFechaEmision;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblImporteTotal;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNombreMercado;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblNumeroTelefono;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JTable tablaConceptos;
    // End of variables declaration//GEN-END:variables
}
