/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import GUI.MenuPrincipal;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.IOException;
import java.net.URI;
import javax.swing.JOptionPane;
import login.RegistrarUsuario;
import mercadoabasto.mercado.Mercado;

/**
 *
 * @author Daniel Juarez
 */
public class Login extends javax.swing.JFrame {

    private Mercado mercado; 
    
    public Login(Mercado mercado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mercado = mercado;
        
        rsscalelabel.RSScaleLabel.setScaleLabel(labelMercado, "D:\\Documentos\\ING. INFORMATICA\\2do Año\\Programacion II\\Laboratorio 2020\\mercadoabastobeta\\src\\imagen\\MercadoSoft.png");
    }

    
  /*  public Login(Mercado mercado, Registro registro){
        
        initComponents();
        this.mercado = mercado;
        this.registro = registro;
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEscritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFacebook = new javax.swing.JButton();
        btnTwitter = new javax.swing.JButton();
        btnYoutebe = new javax.swing.JButton();
        labelMercado = new javax.swing.JLabel();
        PanelNegro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LabelCerrarVentana = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnInicioSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelEscritorio.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel1.setText("Mercado de Abasto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 30));

        btnFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/facebook64_NEGRO.png"))); // NOI18N
        btnFacebook.setBorder(null);
        btnFacebook.setContentAreaFilled(false);
        btnFacebook.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/FACEBOOK64_AZUL.png"))); // NOI18N
        btnFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacebookActionPerformed(evt);
            }
        });
        jPanel1.add(btnFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        btnTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_NEGRO.png"))); // NOI18N
        btnTwitter.setBorder(null);
        btnTwitter.setContentAreaFilled(false);
        btnTwitter.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/twitter64_AZUL.png"))); // NOI18N
        btnTwitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwitterActionPerformed(evt);
            }
        });
        jPanel1.add(btnTwitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        btnYoutebe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_NEGRO.png"))); // NOI18N
        btnYoutebe.setBorder(null);
        btnYoutebe.setContentAreaFilled(false);
        btnYoutebe.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/youtube64_AZUL.png"))); // NOI18N
        btnYoutebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYoutebeActionPerformed(evt);
            }
        });
        jPanel1.add(btnYoutebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));
        jPanel1.add(labelMercado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 280));

        PanelNegro.setBackground(new java.awt.Color(204, 255, 204));
        PanelNegro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/LOGIN128_AZUL_1.png"))); // NOI18N
        PanelNegro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        LabelCerrarVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/CERRAR32_AZUL.png"))); // NOI18N
        LabelCerrarVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelCerrarVentanaMouseClicked(evt);
            }
        });
        PanelNegro.add(LabelCerrarVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimizar32_AZUL.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        PanelNegro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 92, 235));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PASSWORD:");
        PanelNegro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 30));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 92, 235));
        jLabel9.setText("USER:");
        PanelNegro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 60, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BLOQUEAR32_AZUL.png"))); // NOI18N
        PanelNegro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MINI_USER32_AZUL.png"))); // NOI18N
        PanelNegro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(204, 255, 204));
        txtUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Ingrese usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        PanelNegro.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 30));

        txtPassword.setBackground(new java.awt.Color(204, 255, 204));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        PanelNegro.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 180, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(12, 92, 235));
        PanelNegro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 240, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(12, 92, 235));
        PanelNegro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 240, 20));

        btnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        PanelNegro.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 130, -1));

        btnInicioSesion.setBackground(new java.awt.Color(204, 204, 255));
        btnInicioSesion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnInicioSesion.setText("INICIO SESION");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });
        PanelNegro.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, -1));

        PanelEscritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelEscritorio.setLayer(PanelNegro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelEscritorioLayout = new javax.swing.GroupLayout(PanelEscritorio);
        PanelEscritorio.setLayout(PanelEscritorioLayout);
        PanelEscritorioLayout.setHorizontalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelNegro, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        PanelEscritorioLayout.setVerticalGroup(
            PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEscritorioLayout.createSequentialGroup()
                .addGroup(PanelEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelNegro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 769, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelCerrarVentanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelCerrarVentanaMouseClicked
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR EL PROGRAMA?","Confirmar",JOptionPane.YES_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(opcion == JOptionPane.YES_OPTION ){
            this.dispose();
        }
    }//GEN-LAST:event_LabelCerrarVentanaMouseClicked

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        this.txtUsuario.setText("");
        this.txtUsuario.setForeground(new Color(12,92,235));
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        this.txtPassword.setText("");
        this.txtPassword.setForeground(new Color(12,92,235));
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.txtUsuario.setText("Ingrese usuario");
        this.txtPassword.setText("jPasswordField1");
        RegistrarUsuario registrarUsuario = new RegistrarUsuario(mercado);
        Login.PanelEscritorio.add(registrarUsuario); 
        Dimension desktopSize = PanelEscritorio.getSize();
        Dimension FrameSize = registrarUsuario.getSize();
        registrarUsuario.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        
        registrarUsuario.show();

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        // TODO add your handling code here:

        if(verificar()){

            if(this.mercado.getRegistroLogin().getNombreUsuario().equals(txtUsuario.getText()) && this.mercado.getRegistroLogin().getPasswordUsuario().equals(txtPassword.getText())){

                MenuPrincipal menuPrincipal = new MenuPrincipal(this.mercado);
                menuPrincipal.show();
                this.dispose();
            }else{

                JOptionPane.showMessageDialog(null, "¡Usuario y/o Contraseña incorrecto!");
                this.txtUsuario.setText("Ingrese usuario");
                this.txtUsuario.setForeground(Color.black);
                this.txtPassword.setText("jPasswordField1");
                this.txtPassword.setForeground(Color.BLACK);
            }

        }else{
            JOptionPane.showMessageDialog(null, "¡Usuario y/o Contraseña incorrecto!");
            this.txtUsuario.setText("Ingrese usuario");
            this.txtUsuario.setForeground(Color.black);
            this.txtPassword.setText("jPasswordField1");
            this.txtPassword.setForeground(Color.BLACK);
        }

       
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacebookActionPerformed
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.facebook.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnFacebookActionPerformed

    private void btnYoutebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYoutebeActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.youtube.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnYoutebeActionPerformed

    private void btnTwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwitterActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Desktop.getDesktop().browse(URI.create("www.twitter.com"));
        } catch (IOException ex) {
            System.out.println("Error: "+ex);
        }
    }//GEN-LAST:event_btnTwitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Login().setVisible(true);
            }
        });
    }
    
       private boolean verificar(){
   
       if(this.mercado.getRegistroLogin() == null){
           
        return false;
           
       }
     return true; 
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCerrarVentana;
    public static javax.swing.JDesktopPane PanelEscritorio;
    public static javax.swing.JPanel PanelNegro;
    private javax.swing.JButton btnFacebook;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnTwitter;
    private javax.swing.JButton btnYoutebe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelMercado;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
